apiVersion: v1
kind: Pod
metadata:
 name: label-pod
 labels:
  course: docker
  duration: 25hrs
  trainer: siva
 annotations:
  org.docker.kubernetes.image.
spec:
 containers:
  - name: nginx
    image: nginx
