apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxUnavailable: 1 # we asked for 10 and we are ok if 9 pods are available at the time of upgrade.
     maxSurge: 1 # we asked for 10 and we are ok if 11 pods are running at the time of upgrade.
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.22.1
        ports:
        - containerPort: 80
